version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: gitea_postgres
    restart: always
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea_password
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - gitea_net

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - ./gitea:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea_password
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__security__SECRET_KEY=mysecretkey
      - GITEA__server__DOMAIN=localhost
      - GITEA__server__ROOT_URL=http://localhost:3000
      - GITEA__admin__USER=admin
      - GITEA__admin__PASSWORD=123456
    depends_on:
      - postgres
    networks:
      - gitea_net

networks:
  gitea_net:
