version: '3.3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data  # Volume interno na pasta local
    ports:
      - "3001:3001"
    restart: unless-stopped
    