version: "3.8"

services:
  monica:
    image: monicahq/monicahq:latest
    container_name: monica_crm
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=monica
      - DB_USERNAME=monica_user
      - DB_PASSWORD=monica_password
    ports:
      - "8080:80"
    volumes:
      - monica_data:/var/www/html/storage

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=monica_user
      - POSTGRES_PASSWORD=monica_password
      - POSTGRES_DB=monica
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  monica_data:
  pgdata: