version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - jellyfin_config:/app/config  # Corrigido de /config para /app/config
     # - jellyfin_media:/media
      - "C:/Users/Mentor/Music/media:/media"
    environment:
      - PUID=1000  # Adicionado para definir o usuário
      - PGID=1000  # Adicionado para definir o grupo
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    user: "1000:1000"  # Adicionado para garantir permissões corretas

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    depends_on:
      - jellyfin
    ports:
      - "5055:5055"
    volumes:
      - jellyseerr_data:/app/config
    environment:
      - TZ=America/Sao_Paulo
      - JELLYFIN_URL=http://jellyfin:8096
      - JELLYFIN_PORT=8096
      - BASE_URL=/jellyseerr  # Corrigido de URL_BASE para BASE_URL
      - ADMIN_EMAIL=admin@email.com
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=123456
    restart: unless-stopped
    user: "1000:1000"  # Adicionado para garantir permissões corretas

volumes:
  jellyfin_config:
  jellyfin_media:
  jellyseerr_data: